### ISSUE TITLE
remove argparse requirement from setup.py

### ISSUE THREAD

**Issue by blshkv** [riramar/h2rs#1]
https://github.com/riramar/h2rs/blob/main/setup.py#L32

https://pypi.org/project/argparse/
```As of Python >= 2.7 and >= 3.2, the argparse module is maintained within the Python standard library. ```

you can add a conditional flag if you really want to support old versions of python

**Comment by riramar** [comment]
No plans to support old versions. Could you please send a PR totally removing argparse?
I think we can also remove the line https://github.com/riramar/h2rs/blob/main/src/h2rs/h2rs.py#L15.

**Comment by blshkv** [comment]
You can simply remove it from setup.py. it is part of python, so you still need to import it

**Comment by riramar** [comment]
I though you were interested to contribute by providing a push request.
No problem. I'll do it when I have some time.
Thanks for the heads up!

**Comment by blshkv** [comment]
You though right. I found a bug, found a solution and shared with you. Why do you think this is not contributing?

**Comment by riramar** [comment]
I said "contribute by providing a push request".
I didn't say you didn't contribute.
