### ISSUE TITLE
ADD pipe in or -f domains.txt  to take a list of files for stdin

### ISSUE THREAD

**Issue by gprime31** [riramar/h2rs#3]
ADD pipe in or -f domains.txt  to take a list of files for stdin

cat domains.txt  |  h2rs

single line per domain plz :)

**Comment by riramar** [comment]
Just included in my TODO list.
Please fell free to send a PR if you want.
Thanks!

**Comment by gprime31** [comment]
oh ok nice,
also can you make it colored if vuln? 
like red for Not potencial vulnerable
and green for Potencial vulnerable
Thanks.

**Comment by riramar** [comment]
Yes, no problem. I can put some colors. :)
